import type {Metadata} from "next";
import {Cta,Eyebrow,PageHero,Placeholder} from "@/components/UI";
export const metadata:Metadata={title:"About & Approach"};
const steps=[["01","Plan","Review goals, scope, schedule, budget, site conditions, and project requirements."],["02","Coordinate","Align owners, consultants, trades, suppliers, and site teams."],["03","Build","Manage site activity with a focus on safety, efficiency, communication, and quality."],["04","Deliver","Close out with documentation, follow-through, and attention to final details."]];
export default function About(){return <>
  <PageHero eyebrow="ABOUT TMC PROJECTS" title="Built on Clarity, Coordination, and Accountability">TMC Projects brings a focused, practical approach to construction delivery.</PageHero>
  <section className="section"><div className="shell active-grid"><div><Eyebrow>A FOCUSED PARTNER</Eyebrow><h2>Professional Structure.<br/>Hands-On Leadership.</h2><p>We help clients move from planning to completion with clear communication, organized coordination, and hands-on project leadership.</p><p>Our role is to make construction easier to understand and manage—staying close to the work, surfacing decisions early, and following through on the details.</p></div><Placeholder label="Project Coordination and Planning"/></div></section>
  <section className="section muted-section"><div className="shell two-col"><div><Eyebrow>WHAT TMC MEANS</Eyebrow><h2>Trust. Make. Create.</h2></div><div className="intro-copy"><p>TMC reflects the way we work. Trust is built through communication and follow-through. Making is the practical work of managing construction well. Creating is the outcome—spaces that support people, operations, and long-term use.</p></div></div></section>
  <section className="section" id="approach"><div className="shell section-head"><div><Eyebrow>OUR APPROACH</Eyebrow><h2>A Clear Process.<br/>Better Outcomes.</h2><p className="section-deck">Every project needs structure. TMC keeps the process clear, organized, and accountable from start to finish.</p></div></div><div className="shell process">{steps.map(x=><article key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
  <section className="section dark-section"><div className="shell"><Eyebrow>OUR VALUES</Eyebrow><h2>What Guides the Work</h2><div className="dark-cards">{["Clarity","Accountability","Practical execution","Responsiveness","Budget awareness","Site coordination"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div></div></section><Cta/>
</>}
