import Link from "next/link";
import { advantages, Cta, Eyebrow, Placeholder, services } from "@/components/UI";

export default function Home(){return <>
  <section className="home-hero"><div className="shell hero-grid"><div className="hero-copy"><Eyebrow>GENERAL CONTRACTING & PROJECT MANAGEMENT</Eyebrow><h1>Built with Focus.<br/><span>Delivered with Care.</span></h1><p className="hero-line">The right-sized construction partner for projects that need clarity, coordination, and accountability.</p><p>TMC Projects brings professional structure, practical execution, and hands-on attention from planning through closeout.</p><div className="actions"><Link href="/contact" className="button">Start a Project <span aria-hidden>↗</span></Link><Link href="/services" className="text-link">View Services <span aria-hidden>→</span></Link></div></div><Placeholder label="Modern Building Exterior" className="hero-image"/></div><div className="shell hero-note"><span>PLAN</span><p>Build with purpose. Deliver with accountability.</p></div></section>
  <section className="section"><div className="shell two-col"><div><Eyebrow>WHY TMC PROJECTS</Eyebrow><h2>A Right-Sized<br/>Construction Partner</h2></div><div className="intro-copy"><p>TMC Projects is a modern general contracting and project management company built for clients who need professional construction delivery without unnecessary complexity.</p><p>We bring structure where it matters, flexibility where the project needs it, and hands-on attention from planning through closeout.</p></div></div><div className="shell three-cards">{[["01","Clear Planning","We start with clarity—defining scope, schedule, budget, and expectations so every project begins with direction."],["02","Practical Execution","We manage the details that matter on site—coordinating teams, solving problems, and keeping work moving."],["03","Accountable Delivery","We stay close to the work and follow through, keeping communication clear until the project is complete."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="section services-home"><div className="shell section-head"><div><Eyebrow>WHAT WE DO</Eyebrow><h2>Construction Services<br/>That Keep Projects Moving</h2><p className="section-deck">Our services are built around clarity, coordination, and execution—so your project stays on track.</p></div><Link href="/services" className="text-link">Explore all services →</Link></div><div className="shell service-grid">{services.map(s=><article key={s.n} className="service-card"><span>{s.n}</span><div className="line-icon" aria-hidden>⌟</div><h3>{s.t}</h3><p>{s.d}</p><Link href="/services" aria-label={`Learn about ${s.t}`}>Learn more →</Link></article>)}</div></section>
  <section className="section dark-section"><div className="shell why-grid"><div><Eyebrow>THE TMC DIFFERENCE</Eyebrow><h2>Big-Builder Discipline.<br/><span>Small-Team Responsiveness.</span></h2><p>TMC Projects offers a focused alternative for clients who need professional project delivery, practical coordination, and direct communication.</p></div><div className="advantage-list">{advantages.map((a,i)=><article key={a[0]}><span>0{i+1}</span><div><h3>{a[0]}</h3><p>{a[1]}</p></div></article>)}</div></div></section>
  <section className="section"><div className="shell active-grid"><Placeholder label="Active Facility Coordination"/><div><Eyebrow>ACTIVE ENVIRONMENTS</Eyebrow><h2>Built for Spaces That Need to Keep Moving</h2><p>Some projects require more than construction. They require careful planning, safe site coordination, clear communication, and respect for the people using the space.</p><ul className="check-list">{["Active Facility Coordination","Safety Awareness","Minimal Disruption","Clear Site Communication","Responsible Closeout"].map(x=><li key={x}>{x}</li>)}</ul></div></div></section><Cta/>
</>}
